redis_ambassador:
  image: svendowideit/ambassador
  environment:
    - REDIS_PORT_6379_TCP=tcp://192.168.99.101:6379
  expose:
    - "6379"
redis_client:
    image: relateiq/redis-cli
    links:
      - redis_ambassador:redis
